version: "3.8"
services:
  qdrant:
    image: qdrant/qdrant:v1.8.1
    container_name: qdrant
    ports: ["6333:6333"]
    volumes:
      - ./qdrant_storage:/qdrant/storage

  api:
    build: .
    command: uvicorn rag_audio.api:app --host 0.0.0.0 --port 8000
    environment:
      - QDRANT_URL=http://qdrant:6333
    ports: ["8000:8000"]
    depends_on: [qdrant]
